/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IDao, IDaoInterface } from "../IDao";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "unlockTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDao__factory {
  static readonly abi = _abi;
  static createInterface(): IDaoInterface {
    return new utils.Interface(_abi) as IDaoInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IDao {
    return new Contract(address, _abi, signerOrProvider) as IDao;
  }
}
